name: Coverity Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  coverity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake curl tar \
            libcurl4-openssl-dev
          sudo apt-get -y install valgrind libcunit1 libcunit1-doc libcunit1-dev libmsgpack-dev gcovr libtool xsltproc docbook-xsl uuid-dev libcurl4-openssl-dev lcov libmsgpack* libcjson-dev build-essential
              

      - name: Download Coverity Tool
        run: |
          curl -o coverity_tool.tgz \
            "https://scan.coverity.com/download/linux64?token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=webcfg"
              echo "Checking downloaded file..."
          ls -lh coverity_tool.tgz
          file coverity_tool.tgz
          tar xzf coverity_tool.tgz
          pwd
          echo "After extraction:"
          ls -l

      - name: Make Build Directory
        run: mkdir build

      - name: Get rtrouted  Binary
        working-directory: build
        run: |
          ../.github/scripts/rtrouted.sh
          
      - name: Configure (CMake)
        working-directory: build      
        run: |
          cmake .. \
            -DWEBCONFIG_BIN_SUPPORT:BOOL=true \
            -DWAN_FAILOVER_SUPPORTED:BOOL=true \
            -DBUILD_GIT:BOOL=true
          ps aux 
          export RBUS_ROOT=${HOME}/rbus
          export RBUS_INSTALL_DIR=${RBUS_ROOT}/install && \
          export LD_LIBRARY_PATH=${RBUS_INSTALL_DIR}/usr/lib/rbus_temp_lib:${LD_LIBRARY_PATH}            
          export C_INCLUDE_PATH=${RBUS_INSTALL_DIR}/usr/include                   
          mkdir _install
          mkdir _install/lib
          cp ${RBUS_INSTALL_DIR}/usr/lib/librbus* _install/lib                 

      - name: Build with Coverity (PR only)
        if: github.event_name == 'pull_request'
        run: |
          export PATH=${GITHUB_WORKSPACE}/cov-analysis-linux64-2024.12.1/bin:$PATH
          cd build
          cov-build --dir cov-int make

      - name: Analyze (PR only)
        if: github.event_name == 'pull_request'
        run: |
          export PATH=${GITHUB_WORKSPACE}/cov-analysis-linux64-2024.12.1/bin:$PATH
          
          cd build
          cov-build --dir cov-int make -j$(nproc)          

      - name: Stop rtrouted
        run: |
          killall -9 rtrouted
          
      - name: Upload results (PR artifact)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: coverity-results
          path: build/cov-int

      - name: Build with Coverity (master upload)
        if: github.ref == 'refs/heads/master'
        run: |
          export PATH=$(pwd)/cov-analysis-linux64-2024.12.1/bin:$PATH
          cd build
          cov-build --dir cov-int make -j$(nproc)

      - name: Submit to Coverity Scan (master only)
        if: github.ref == 'refs/heads/master'
        run: |
          cd build
          tar czvf cov-int.tgz cov-int

          curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} \
               --form email=${{ secrets.COVERITY_SCAN_EMAIL }} \
               --form file=@cov-int.tgz \
               --form version="${{ github.sha }}" \
               --form description="GitHub Actions build" \
               https://scan.coverity.com/builds
